export const INITIAL_STATE = {
  geodaProxy: null,
  storedData: {},
  storedGeojson: {},
  storedLisaData: {},
  storedCSV: {},
  cols: {},
  currentData: '',
  chartData: [{}],
  centroids: {},
  dates: {},
  currDate: '',
  currDateIndex: '',
  startDateIndex: '',
  currentVariable: 'Confirmed Count per 100K Population',
  currentMethod: 'natural_breaks',
  currentOverlay: '',
  currentResource: '',
  dataParams: {
    numerator: 'cases',
    nType: 'time-series',
    nProperty: null,
    nRange: 7,
    nIndex:null,
    denominator: 'properties',
    dType: 'characteristic',
    dProperty: 'population',
    dRange:null,
    dIndex:null,
    scale:100000,
  },
  mapParams: {
    mapType: 'natural_breaks',
    bins: {
      bins: [],
      breaks: []
    },
    binMode: '',
    fixedScale: null,
    nBins: 8,
    use3d: false,
    activeGeoid: '',
    overlay: '',
    resource: '',
    colorScale: [
      [240,240,240],
      [255,255,204],
      [255,237,160],
      [254,217,118],
      [254,178,76],
      [253,141,60],
      [252,78,42],
      [227,26,28],
      [177,0,38],
    ],
  },
  storedRange: null,
  currentGeoid: '',
  sidebarData: {},
  anchorEl: null,
};